//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietOrder
    {
        public int CTOrderID { get; set; }
        public int OrderID { get; set; }
        public int MonID { get; set; }
        public int SoLuong { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> ThoiGianHoanTat { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
