//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public KhuyenMai()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int KhuyenMaiID { get; set; }
        public string MaVoucher { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaTriGiam { get; set; }
        public string KieuGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoLanSuDungToiDa { get; set; }
        public string DieuKienApDung { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
