//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPMEntities1 : DbContext
    {
        public CNPMEntities1()
            : base("name=CNPMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietOrder> ChiTietOrders { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<Mon> Mons { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<NhomMon> NhomMons { get; set; }
        public DbSet<ORDER> ORDERs { get; set; }
        public DbSet<PhanQuyen> PhanQuyens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
