//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mon
    {
        public Mon()
        {
            this.ChiTietOrders = new HashSet<ChiTietOrder>();
        }
    
        public int MonID { get; set; }
        public string TenMon { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> NhomMonID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<ChiTietOrder> ChiTietOrders { get; set; }
        public virtual NhomMon NhomMon { get; set; }
    }
}
