//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomMon
    {
        public NhomMon()
        {
            this.Mons = new HashSet<Mon>();
        }
    
        public int NhomMonID { get; set; }
        public string TenNhom { get; set; }
        public string MoTa { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<Mon> Mons { get; set; }
    }
}
