//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.ChiTietOrders = new HashSet<ChiTietOrder>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> ChiNhanhID { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> KhuyenMaiID { get; set; }
    
        public virtual ICollection<ChiTietOrder> ChiTietOrders { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
