//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miss1988.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public PhanQuyen()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int QuyenID { get; set; }
        public string TenQuyen { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
